version: '3.9'

services:
  blacklistservice:
    image: blacklist_service:latest
    container_name: blacklist
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    networks:
      - blacklist
    depends_on:
      -  mongo  

  mongo:
    image : mongo:5.0.4
    container_name: mongo
    environment:
    - PUID=1000
    - PGID=1000
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
    - mongodb-data-blacklist:/data/db
    ports:
    - 27017:27017
    networks:
      - blacklist    

volumes:
  mongodb-data-blacklist:

networks:
  blacklist:
